"""Template-based document generation engine."""
import os
from datetime import datetime
from pathlib import Path
from typing import Any, Optional
from jinja2 import Environment, FileSystemLoader, select_autoescape

from backend.app.core.config import settings

# Template directory
TEMPLATE_DIR = Path(__file__).parent.parent.parent / "templates"

# Set up Jinja2 environment
_env = Environment(
    loader=FileSystemLoader(str(TEMPLATE_DIR)),
    autoescape=select_autoescape(["html", "xml"]),
    trim_blocks=True,
    lstrip_blocks=True,
)


def render_template(template_name: str, context: dict[str, Any]) -> str:
    """Render a Jinja2 template with given context."""
    template = _env.get_template(template_name)
    return template.render(**context, now=datetime.now())


def _md_to_html(markdown_content: str, title: str = "Document") -> str:
    """Convert markdown to styled HTML."""
    import markdown
    md_html = markdown.markdown(
        markdown_content,
        extensions=["tables", "fenced_code", "codehilite", "nl2br"],
    )
    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{ font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 12pt; line-height: 1.6; max-width: 700px; margin: 0 auto; padding: 40px; color: #333; }}
  h1 {{ font-size: 20pt; border-bottom: 2px solid #2563eb; padding-bottom: 8px; color: #1e3a5f; }}
  h2 {{ font-size: 16pt; color: #2563eb; margin-top: 24px; }}
  h3 {{ font-size: 13pt; color: #333; }}
  table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
  th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
  th {{ background-color: #f0f4ff; font-weight: bold; }}
  code {{ background: #f5f5f5; padding: 2px 6px; border-radius: 3px; font-size: 10pt; }}
  pre {{ background: #f5f5f5; padding: 12px; border-radius: 6px; overflow-x: auto; }}
  blockquote {{ border-left: 3px solid #2563eb; padding-left: 16px; color: #666; margin: 16px 0; }}
  .footer {{ margin-top: 40px; font-size: 9pt; color: #999; text-align: center; }}
</style>
</head>
<body>
{md_html}
<div class="footer">
  <p>Generated by InsureAI v{settings.app_version} on {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
</div>
</body>
</html>"""


def render_markdown_to_pdf(markdown_content: str, output_path: str, title: str = "Document") -> str:
    """Render markdown content to a PDF file using WeasyPrint.
    Falls back to saving as .html if PDF generation is unavailable.
    """
    html = _md_to_html(markdown_content, title)

    try:
        from weasyprint import HTML
        HTML(string=html).write_pdf(output_path)
        return output_path
    except (OSError, ImportError) as e:
        # Fallback: save as HTML if WeasyPrint is unavailable
        html_path = output_path.rsplit(".", 1)[0] + ".html"
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        Path(html_path).write_text(html, encoding="utf-8")
        return html_path


def render_template_to_pdf(
    template_name: str,
    context: dict[str, Any],
    output_filename: Optional[str] = None,
) -> str:
    """Render a Jinja2 template and convert to PDF."""
    html_content = render_template(template_name, context)

    if output_filename is None:
        output_filename = f"{template_name.replace('.j2', '')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    output_path = Path(settings.output_dir) / output_filename
    from weasyprint import HTML
    HTML(string=html_content).write_pdf(str(output_path))
    return str(output_path)


def render_template_to_docx(
    template_name: str,
    context: dict[str, Any],
    output_filename: Optional[str] = None,
) -> str:
    """Render a Jinja2 template and create a DOCX file (markdown content within)."""
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    md_content = render_template(template_name, context)

    if output_filename is None:
        output_filename = f"{template_name.replace('.j2', '')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"

    output_path = Path(settings.output_dir) / output_filename

    doc = Document()
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)

    # Simple approach: split by lines and add paragraphs
    for line in md_content.split("\n"):
        line = line.strip()
        if not line:
            continue
        if line.startswith("# "):
            heading = doc.add_heading(line[2:], level=1)
        elif line.startswith("## "):
            heading = doc.add_heading(line[2:], level=2)
        elif line.startswith("### "):
            heading = doc.add_heading(line[2:], level=3)
        elif line.startswith("- "):
            doc.add_paragraph(line[2:], style="List Bullet")
        elif line.startswith("|"):
            # Skip table rows for simplicity (can be enhanced)
            doc.add_paragraph(line, style="Normal")
        else:
            doc.add_paragraph(line, style="Normal")

    doc.save(str(output_path))
    return str(output_path)
